using UnityEngine;
using System.Collections.Generic;
using System;

public class MainThreadDispatcher : MonoBehaviour
{
    private static readonly Queue<Action> _executionQueue = new Queue<Action>();

    public void Update() {
        lock(_executionQueue) {
            while (_executionQueue.Count > 0) {
                _executionQueue.Dequeue().Invoke();
            }
        }
    }

    public static void Enqueue(Action action) {
        if (action == null) {
            throw new ArgumentNullException("action");
        }

        lock(_executionQueue) {
            _executionQueue.Enqueue(action);
        }
    }
}
